[build]
builder = "nixpacks"

[build.buildCommand]
cmd = "npm ci && npm run build"

[build.installCommand]
cmd = "npm ci --production=false"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
PORT = "$PORT"
